name: vn_map_app
description: Vietnam map desktop application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.2.1
  go_router: ^14.2.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/geo/
    - assets/geo/provinces/
    - assets/data/
