// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRqZQPE_0emFto1NQPntR-JJ2CriWuuE',
    appId: '1:166713477101:web:b37e642f8739a967f709e4',
    messagingSenderId: '166713477101',
    projectId: 'vietmap-9c90d',
    authDomain: 'vietmap-9c90d.firebaseapp.com',
    storageBucket: 'vietmap-9c90d.firebasestorage.app',
    measurementId: 'G-69VX5SVCLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC695v4Uakna7w-quB_agxnVlbm5qI8C-M',
    appId: '1:166713477101:android:6fc41dd44d477265f709e4',
    messagingSenderId: '166713477101',
    projectId: 'vietmap-9c90d',
    storageBucket: 'vietmap-9c90d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebJ2ACohfZx4Zc22Q651rU5djEzYjSF8',
    appId: '1:166713477101:ios:e84ad55b7d87e14af709e4',
    messagingSenderId: '166713477101',
    projectId: 'vietmap-9c90d',
    storageBucket: 'vietmap-9c90d.firebasestorage.app',
    iosBundleId: 'com.example.vnMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebJ2ACohfZx4Zc22Q651rU5djEzYjSF8',
    appId: '1:166713477101:ios:e84ad55b7d87e14af709e4',
    messagingSenderId: '166713477101',
    projectId: 'vietmap-9c90d',
    storageBucket: 'vietmap-9c90d.firebasestorage.app',
    iosBundleId: 'com.example.vnMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCRqZQPE_0emFto1NQPntR-JJ2CriWuuE',
    appId: '1:166713477101:web:b7c6eb5a6d7e4b17f709e4',
    messagingSenderId: '166713477101',
    projectId: 'vietmap-9c90d',
    authDomain: 'vietmap-9c90d.firebaseapp.com',
    storageBucket: 'vietmap-9c90d.firebasestorage.app',
    measurementId: 'G-7JZQ7EQ32S',
  );
}
